### ISSUE TITLE
dual directions feedback trouble...

### ISSUE THREAD

**Issue by moebiussurfing** [c-mendoza/ofxRemoteParameters#5]
Hey @c-mendoza ,

I am trying to enable feedback on the client-side when the server parameters changed.

But when adding the sync command on the variable callback on server,
the client sliders it's stuck. I mean when controlling from the client side.

So the feedback to mirror both sides params seems that can't work permanently..... 
I mean that we need to manually pick only one of the both modes:
(1) Control by the client or (2) control by the server sliders.

Are you experiencing the same behavior there?

I am on Windows / VS 2017.

```
void ofApp::draw()
{
	static float _circleRadius;
	if (_circleRadius != circleRadius) {
		_circleRadius = circleRadius;
		paramServer.syncParameters();
	}

	ofBackgroundGradient(ofColor::gray, ofColor::blueSteel);
	ofFill();
	ofSetColor(circleColor);
	ofDrawEllipse(circlePosition, circleRadius * 0.5, circleRadius * 0.5);
	gui.draw();
}
```

**Comment by c-mendoza** [comment]
Right, you don't want to do that way because you will cause feedback, and the client might lock up. The syncParameters() method should be used sparingly, because it sends the whole model to the client, which then needs to parse it, and will send those value "updates" back to the server. There should probably be a way to suppress sending data to the server, which would probably help a bit, But even if that was implemented, hitting the client repeatedly with syncParameters() is going to slow it down, because parsing the model is slow. If you need to automate the synchronization, I would probably call syncParameters() at the end of a timer that restarts whenever you change a value on the server. That way, if you make many changes before the timer is up, the server doesn't syncParameters() constantly.

**Comment by moebiussurfing** [comment]
Ok. thanks.
To get bidirectional... Do you think that using a server and another extra client object should be fine?

EDIT:

The TouchOSC device that is receiving (of course) does not require to be connected as is not a remoteParam server...
Maybe could be a mode just sending. Then could get the OSC structure locally 
(from the server object or the passed group) or something.
